version: "3"

services:
  sonarqube:
    image: mc1arke/sonarqube-with-community-branch-plugin:10.3-community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_conf:/opt/sonarqube/conf

    ports:
      - "9000:9000"
    networks:
      - sonarqube
    restart: always
  db:
    image: postgres:12
    hostname: sonarqube-postgresql-db
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./sonarqube-db/postgresql:/var/lib/postgresql
      - ./sonarqube-db/postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarqube
    restart: always

networks:
  sonarqube:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_conf:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  posgresql_data: 